### PR TITLE
Use node-FreeType2 v1

### LINKED ISSUE #8: Installing “font-viewer@0.3.0” failed (tried 3x)
Installing “font-viewer@0.3.0” failed.Hide output…

> freetype2@0.2.3 install D:\TEMP\TMP\apm-install-dir-1151027-3976-hfpapg\node_modules\font-viewer\node_modules\freetype2
> node-gyp rebuild

D:\TEMP\TMP\apm-install-dir-1151027-3976-hfpapg\node_modules\font-viewer\node_modules\freetype2>if not defined npm_config_node_gyp (node "C:\Users\Anandajoti\AppData\Local\atom\app-1.3.0-beta6\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Anandajoti\AppData\Local\atom\app-1.3.0-beta6\resources\app\apm\bin\node.exe" "C:\Users\Anandajoti\AppData\Local\atom\app-1.3.0-beta6\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Anandajoti\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Anandajoti\.atom\.apmrc" "install" "D:\TEMP\TMP\d-1151027-3976-jo7q8n\package.tgz" "--target=0.34.3" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

### LINKED ISSUE #14: It wouldn't install
This is the error message:

**Installing “font-viewer@0.3.1” failed.

> freetype2@0.3.0 install C:\Users\DECLAR~1\AppData\Local\Temp\apm-install-dir-116510-62012-h2ujh4\node_modules\font-viewer\node_modules\freetype2
> node-gyp rebuild

C:\Users\DECLAR~1\AppData\Local\Temp\apm-install-dir-116510-62012-h2ujh4\node_modules\font-viewer\node_modules\freetype2>if not defined npm_config_node_gyp (node "C:\Users\DeclaredDig10\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\DeclaredDig10\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\DeclaredDig10\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\DeclaredDig10\.atom\.apm\.apmrc" "--userconfig" "C:\Users\DeclaredDig10\.atom\.apmrc" "install" "C:\Users\DECLAR~1\AppData\Local\Temp\d-116510-62012-szbc04\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.**

### LINKED ISSUE #22: Broken on modern python
```


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Python35\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\durr\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\durr\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\durr\AppData\Local\Temp\apm-install-dir-11887-2264-f69vg2.yxpiffajor\node_modules\font-viewer\node_modules\freetype2
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\durr\AppData\Local\Temp\apm-install-dir-11887-2264-f69vg2.yxpiffajor\package.json'
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No description
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No repository field.
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No README data
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\durr\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\durr\\.atom\\.apmrc" "install" "C:\\Users\\durr\\AppData\\Local\\Temp\\d-11887-2264-1mfg46z.c6yz99hpvi\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freetype2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\durr\AppData\Local\Temp\apm-install-dir-11887-2264-f69vg2.yxpiffajor\npm-debug.log
npm ERR! code 1

```

Py2k is dead. 

(Title rename because I mis-read the error output)

### LINKED ISSUE #24: Installing “font-viewer@0.4.0” failed
Installing “font-viewer@0.4.0” failed.

> freetype2@0.3.0 install /private/var/folders/1x/b3swxcss1plfmjf2cm06r0jc0000gn/T/apm-install-dir-202095-4193-bpfitf.dsclj/node_modules/font-viewer/node_modules/freetype2
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/1x/b3swxcss1plfmjf2cm06r0jc0000gn/T/apm-install-dir-202095-4193-bpfitf.dsclj/node_modules/font-viewer/node_modules/freetype2
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/1x/b3swxcss1plfmjf2cm06r0jc0000gn/T/apm-install-dir-202095-4193-bpfitf.dsclj/package.json'
npm WARN apm-install-dir-202095-4193-bpfitf.dsclj No description
npm WARN apm-install-dir-202095-4193-bpfitf.dsclj No repository field.
npm WARN apm-install-dir-202095-4193-bpfitf.dsclj No README data
npm WARN apm-install-dir-202095-4193-bpfitf.dsclj No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freetype2@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/walit/.atom/.apm/_logs/2020-10-05T13_41_55_817Z-debug.log

### LINKED ISSUE #25: Use node-freetype v1

### PR DESCRIPTION
**Pull request by aminya**
This version switches to freetype2 v1 which includes prebuilt binaries. That means all of the building issues are fixed.

Fixes #25 
Fixes #24 
Fixes #22
Fixes #14
Fixes #8

### CODE REVIEW

File: lib/font-viewer.js [hunk 1]
```diff
@@ -73,15 +73,14 @@ export default class FontViewer {
...
+      const face = NewMemoryFace(buffer, 0);
 
-      while (gindex.gindex !== 0) {
+      let charcode = face.getFirstChar()
+      let num = 0
+      while (charcode !== null) {
+        num++
         chars.push(charcode)
-        charcode = ft.Get_Next_Char(face, charcode, gindex)
+        charcode = face.getNextChar(num)
```
Comment (aminya) [inline lib/font-viewer.js:83]: This currently does not work. Do you have any idea how the API is changed here? 
@Julusian

Comment (aminya) [reply lib/font-viewer.js]: OK. I figured it out for now.
